---
- name: Other essential packages
  community.general.pacman:
    name:
      - extra/git
      - core/man-db
      - core/curl
      - extra/wget
      - extra/vim
      - extra/tree
      - extra/lsof
      - extra/xclip
    state: present
  become: true
