---
- name: Other essential packages
  community.general.pacman:
    name:
      - core/coreutils
      - core/man-db
      - core/curl
      - extra/git
      - extra/wget
      - extra/vim
      - extra/tree
      - extra/lsof
      - extra/xclip
      - extra/strace
      - community/pwgen
    state: present
  become: true
