---
- name: Other essential packages
  pacman:
    name:
      - extra/git
      - core/man-db
      - core/curl
      - extra/wget
      - extra/vim
      - extra/tree
      - extra/lsof
      - extra/python-pip
    state: present
  become: true
