---
- name: Other essential packages
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.coreutils }}"
      - "{{ config.packages.pacman.man-db }}"
      - "{{ config.packages.pacman.curl }}"
      - "{{ config.packages.pacman.git }}"
      - "{{ config.packages.pacman.wget }}"
      - "{{ config.packages.pacman.vim }}"
      - "{{ config.packages.pacman.tree }}"
      - "{{ config.packages.pacman.lsof }}"
      - "{{ config.packages.pacman.xclip }}"
      - "{{ config.packages.pacman.strace }}"
      - "{{ config.packages.pacman.pwgen }}"
    state: present
  become: true
