---
# etckeeper config
#
# Check the status with:
#   sudo etckeeper vcs status
#
- name: Install etckeeper
  community.general.pacman:
    name: community/etckeeper
    state: present
  become: true

- name: Init etckeeper and first commit
  ansible.builtin.command:
    cmd: |
      etckeeper init
      git config --local user.name root
      git config --local user.email root@{{ arg_hostname }}
      etckeeper commit -m 'Initial commit'
    chdir: /etc
  become: true
