---
# https://www.gnu.org/software/freefont/
- name: Install GNU Free Fonts
  community.general.pacman:
    name: extra/gnu-free-fonts
    state: present
  become: true

# https://fonts.google.com/noto
- name: Install noto-fonts
  community.general.pacman:
    name:
      - extra/noto-fonts
      - extra/noto-fonts-extra
    state: present
  become: true

# https://www.jetbrains.com/lp/mono/
# https://www.nerdfonts.com/font-downloads
- name: Install JetBrains Mono Nerd Fonts
  kewlfft.aur.aur:
    use: yay
    name: nerd-fonts-jetbrains-mono
    state: present
