---
# Fonts
#
# List fonts
#   fc-list
#
# Match a font from the list
#   fc-match emoji
#

# https://www.gnu.org/software/freefont/
- name: Install GNU Free Fonts
  community.general.pacman: name="{{ config.packages.pacman.gnu_free_fonts }}" state=present
  become: true

# https://fonts.google.com/noto
- name: Install noto-fonts
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.noto_fonts }}"
      - "{{ config.packages.pacman.noto_fonts_extra }}"
      - "{{ config.packages.pacman.noto_fonts_emoji }}"
      - "{{ config.packages.pacman.noto_fonts_cjk }}"
    state: present
  become: true

# https://www.jetbrains.com/lp/mono/
# https://www.nerdfonts.com/font-downloads
- name: Install JetBrains Mono Nerd Fonts
  kewlfft.aur.aur:
    use: yay
    name: "{{ config.packages.aur.nerd_fonts_jetbrains_mono }}"
    state: present

- name: Setup fontconfig
  block:
    - name: Create fontconfig directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'XDG_CONFIG_HOME') }}/fontconfig"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0700
        state: directory

    - name: Create config for fonts.conf
      ansible.builtin.copy:
        dest: "{{ lookup('env', 'XDG_CONFIG_HOME') }}/fontconfig/fonts.conf"
        content: |
          <?xml version="1.0"?>
          <!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
          <fontconfig>
          <alias>
             <family>monospace</family>
             <prefer>
               <family>JetBrainsMono Nerd Font Mono</family>
               <family>Noto Color Emoji</family>
             </prefer>
           </alias>
          </fontconfig>
        mode: 0644

# vim: ft=yaml.ansible
