---
# https://www.gnu.org/software/freefont/
- name: Install GNU Free Fonts
  pacman:
    name: extra/gnu-free-fonts
    state: present
  become: true

# https://www.jetbrains.com/lp/mono/
# https://www.nerdfonts.com/font-downloads
- name: Install JetBrains Mono Nerd Fonts
  kewlfft.aur.aur:
    use: yay
    name: nerd-fonts-jetbrains-mono
    state: present
