---
# Fonts
#
# List fonts
#   fc-list
#
# Match a font from the list
#   fc-match emoji
#

# https://www.gnu.org/software/freefont/
- name: Install GNU Free Fonts
  community.general.pacman:
    name: extra/gnu-free-fonts
    state: present
  become: true

# https://fonts.google.com/noto
- name: Install noto-fonts
  community.general.pacman:
    name:
      - extra/noto-fonts
      - extra/noto-fonts-extra
      - extra/noto-fonts-emoji
    state: present
  become: true

# https://www.jetbrains.com/lp/mono/
# https://www.nerdfonts.com/font-downloads
- name: Install JetBrains Mono Nerd Fonts
  kewlfft.aur.aur:
    use: yay
    name: nerd-fonts-jetbrains-mono
    state: present

- name: Setup fontconfig
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/fontconfig/fonts.conf"
    content: |
      <?xml version="1.0"?>
      <!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
      <fontconfig>
      <alias>
         <family>monospace</family>
         <prefer>
           <family>JetBrainsMono Nerd Font Mono</family>
           <family>Noto Color Emoji</family>
         </prefer>
       </alias>
      </fontconfig>
    mode: 0644
