---
- name: Get the current hostname
  ansible.builtin.command: cat /etc/hostname
  changed_when: false
  register: current_hostname

- name: Check if the hostname is same as argument
  fail:
    msg: |
      System hostname not same as the argument.
      Double check the system you install.
      system "{{ current_hostname.stdout }}"
      argument "{{ arg_hostname }}"
  when: current_hostname.stdout != arg_hostname

- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ arg_hostname }}"
    use: systemd
  become: true
