---
- name: Base
  hosts: all
  tags: base
  vars:
    yay_command: /usr/bin/yay
    workbench_dir: /opt/workbench
    yay_install_dir: "{{ workbench_dir }}/yay"
    pacman_updated_file: "{{ workbench_dir }}/.ansible_pacman_updated"
  tasks:
    - name: Set hostname
      ansible.builtin.import_tasks: hostname.yml
      tags: base.hostname

    - name: Have a workbench folder belonging to user
      ansible.builtin.file:
        path: "{{ workbench_dir }}"
        # equivalent of `sudo chown -R $USER:$USER <path>`
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0700
        state: directory
      become: true
      register: workbench_folder

    - name: Setup pacman
      ansible.builtin.import_tasks: pacman.yml
      tags: base.pacman

    - name: Install yay
      ansible.builtin.import_tasks: yay.yml
      tags: base.yay

    - name: Essential packages
      ansible.builtin.import_tasks: essential.yml
      tags: base.essential

    - name: Setup etckeeper
      ansible.builtin.import_tasks: etckeeper.yml
      tags: base.etckeeper

    - name: Setup fonts
      ansible.builtin.import_tasks: fonts.yml
      tags: base.fonts

    - name: Setup xdg
      ansible.builtin.import_tasks: xdg.yml
      tags: base.xdg

    - name: Network tools
      ansible.builtin.import_tasks: network.yml
      tags: base.network

    - name: GnuPG
      ansible.builtin.import_tasks: gnupg.yml
      tags: base.gnupg

    - name: pass
      ansible.builtin.import_tasks: pass.yml
      tags: base.pass

    - name: qrcode
      ansible.builtin.import_tasks: qrcode.yml
      tags: base.qrcode
