#!/usr/bin/env bash

ansible-playbook -v "$@" main.yml --tags="""
base,
ntp,
bluetooth,
packages.cli_fetch,
packages.cli_utils,
packages.docker,
packages.nvim,
packages.pip.python_tools,
packages.podman,
packages.tmux,
packages.zsh,
gui.alacritty,
gui.brave,
gui.chrome,
gui.chromium,
gui.dbeaver,
gui.firefox,
gui.flameshot,
gui.gedit,
gui.gnome_disk_utility,
gui.gthumb,
gui.libreoffice,
gui.meld,
gui.slack,
gui.vscode,
"""
