- name: GUI
  hosts: all
  tasks:
    - name: Install alacritty terminal  # https://github.com/alacritty/alacritty
      pacman: name=community/alacritty state=present
      become: true
      tags: gui__alacritty

    - name: Install meld
      pacman: name=extra/meld  # https://meldmerge.org state=present
      become: true
      tags: gui__meld

    - name: Install flameshot  # https://github.com/flameshot-org/flameshot
      pacman: name=community/flameshot state=present
      become: true
      tags: gui__flameshot

    - name: Install gedit
      pacman: name=extra/gedit state=present
      become: true
      tags:
        - gui__gedit

    - name: Install Chromium
      pacman: name=extra/chromium state=present
      become: true
      tags: gui__chromium

    - name: Install Chrome
      kewlfft.aur.aur:
        use: yay
        name: google-chrome
        state: present
      tags: gui__chrome

    - name: Install Firefox
      pacman: name=extra/firefox state=present
      become: true
      tags: gui__firefox

    - name: Install Brave  # https://brave.com
      kewlfft.aur.aur:
        use: yay
        name: brave-bin
        state: present
      tags: gui__brave

    - name: Install vscode
      pacman: name=community/code state=present
      become: true
      tags: gui__vscode

    - name: Install LibreOffice
      pacman: name=extra/libreoffice-fresh state=present
      become: true
      tags: gui__libreoffice

    - name: Install Slack desktop
      kewlfft.aur.aur:
        use: yay
        name: slack-desktop
        state: present
      tags: gui__slack

    - name: Install DBeaver  # https://dbeaver.io/
      pacman: name=community/dbeaver state=present
      become: true
      tags: gui__dbeaver

    - name: Install RStudio  # https://www.rstudio.com/
      kewlfft.aur.aur:
        use: yay
        name: rstudio-desktop-bin
        state: present
      tags: gui__rstudio

    - name: Install Signal
      pacman: name=community/signal-desktop state=present
      become: true
      tags: gui__signal

    - name: Install Telegram
      pacman: name=community/telegram-desktop state=present
      become: true
      tags: gui__telegram

    - name: Install Wireshark  # https://www.wireshark.org/
      pacman:
        name:
          - community/wireshark-cli
          - community/wireshark-qt
        state: present
      become: true
      tags: gui__wireshark

    - name: Install VLC
      pacman: name=extra/vlc state=present
      become: true
      tags: gui__vlc

    - name: Install keepassxc  # https://keepassxc.org/
      pacman: name=community/keepassxc state=present
      become: true
      tags: gui__keepassxc

    - name: Install gThumb  # https://wiki.gnome.org/Apps/Gthumb
      pacman: name=extra/gthumb state=present
      become: true
      tags: gui__gthumb

    - name: Install xcolor  # https://github.com/Soft/xcolor
      pacman: name=community/xcolor state=present
      become: true
      tags: gui__xcolor

    - name: Install magicavoxel  # https://ephtracy.github.io/
      kewlfft.aur.aur:
        use: yay
        name: magicavoxel
        state: present
      tags: gui__magicavoxel

    - name: Install virtualization
      import_tasks: virtualization.yml
      tags: gui__virtualization
