---
- name: GUI
  hosts: all
  tags: gui
  tasks:
    # https://github.com/alacritty/alacritty
    - name: Install Alacritty terminal
      community.general.pacman: name="{{ config.packages.pacman.alacritty }}" state=present
      become: true
      tags: gui.alacritty

    - name: Setup gedit
      ansible.builtin.import_tasks: gedit.yml
      tags: gui.gedit

    - name: Install Firefox
      community.general.pacman: name="{{ config.packages.pacman.firefox }}" state=present
      become: true
      tags: gui.firefox

    - name: Install Chromium
      community.general.pacman: name="{{ config.packages.pacman.chromium }}" state=present
      become: true
      tags: gui.chromium

    - name: Install Google Chrome
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.google_chrome }}"
        state: present
      tags: gui.chrome

    # https://brave.com
    - name: Install Brave browser
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.brave_bin }}"
        state: present
      tags: gui.brave

    # https://wiki.archlinux.org/title/Visual_Studio_Code (open source version)
    - name: Install code
      community.general.pacman: name="{{ config.packages.pacman.code }}" state=present
      tags: gui.code

    # https://code.visualstudio.com/ (MS version)
    - name: Install Visual Studio Code
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.visual_studio_code_bin }}"
        state: present
      tags: gui.vscode

    # https://dbeaver.io/
    - name: Install DBeaver
      community.general.pacman: name="{{ config.packages.pacman.dbeaver }}" state=present
      become: true
      tags: gui.dbeaver

    - name: Install LibreOffice
      community.general.pacman: name="{{ config.packages.pacman.libreoffice_fresh }}" state=present
      become: true
      tags: gui.libreoffice

    # https://www.thunderbird.net
    - name: Setup Thunderbird
      ansible.builtin.import_tasks: thunderbird.yml
      tags: gui.thunderbird

    - name: Install Slack desktop
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.slack_desktop }}"
        state: present
      tags: gui.slack

    # https://www.rstudio.com/
    - name: Install RStudio
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.rstudio_desktop_bin }}"
        state: present
      tags: gui.rstudio

    - name: Install Signal
      community.general.pacman: name="{{ config.packages.pacman.signal_desktop }}" state=present
      become: true
      tags: gui.signal

    - name: Install Telegram
      community.general.pacman: name="{{ config.packages.pacman.telegram_desktop }}" state=present
      become: true
      tags: gui.telegram

    # https://www.wireshark.org/
    - name: Install Wireshark
      ansible.builtin.import_tasks: wireshark.yml
      tags: gui.wireshark

    - name: Install VLC
      community.general.pacman: name="{{ config.packages.pacman.vlc }}" state=present
      become: true
      tags: gui.vlc

    # https://keepassxc.org/
    - name: Install keepassxc
      community.general.pacman: name="{{ config.packages.pacman.keepassxc }}" state=present
      become: true
      tags: gui.keepassxc

    # https://www.gimp.org/
    - name: Install gimp
      community.general.pacman: name="{{ config.packages.pacman.gimp }}" state=present
      become: true
      tags: gui.gimp

    # https://wiki.gnome.org/Apps/Gthumb
    - name: Install gThumb
      community.general.pacman: name="{{ config.packages.pacman.gthumb }}" state=present
      become: true
      tags: gui.gthumb

    # https://github.com/Soft/xcolor
    - name: Install xcolor
      community.general.pacman: name="{{ config.packages.pacman.xcolor }}" state=present
      become: true
      tags: gui.xcolor

    # https://ephtracy.github.io/
    - name: Install magicavoxel
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.magicavoxel }}"
        state: present
      tags: gui.magicavoxel

    - name: Install gnome-disk-utility
      community.general.pacman: name="{{ config.packages.pacman.gnome_disk_utility }}" state=present
      become: true
      tags: gui.gnome_disk_utility

    # https://meldmerge.org
    - name: Install meld
      community.general.pacman: name="{{ config.packages.pacman.meld }}" state=present
      become: true
      tags: gui.meld

    # https://www.vagrantup.com/
    - name: Install vagrant
      community.general.pacman: name="{{ config.packages.pacman.vagrant }}" state=present
      become: true
      tags: gui.vagrant

    # https://www.virtualbox.org/
    - name: Install VirtualBox
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.virtualbox }}"
          - "{{ config.packages.pacman.virtualbox_guest_utils }}"
        state: present
      become: true
      tags: gui.virtualbox

    - name: Install gnome-boxes
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.libvirt }}"
          - "{{ config.packages.pacman.gnome_boxes }}"
          - "{{ config.packages.pacman.virt_manager }}"
        state: present
      become: true
      tags: gui.gnome_boxes

    # Linux device manager for Logitech devices
    # https://pwr-solaar.github.io/Solaar/
    - name: Install solaar
      community.general.pacman: name="{{ config.packages.pacman.solaar }}" state=present
      become: true
      tags: gui.solaar
