---
- name: GUI
  hosts: all
  tags: gui
  tasks:
    # https://github.com/alacritty/alacritty
    - name: Install Alacritty terminal
      community.general.pacman: name=community/alacritty state=present
      become: true
      tags: gui.alacritty

    - name: Install gedit
      community.general.pacman: name=extra/gedit state=present
      become: true
      tags: gui.gedit

    - name: Install Chrome
      kewlfft.aur.aur:
        use: yay
        name: google-chrome
        state: present
      tags: gui.chrome

    - name: Install Chromium
      community.general.pacman: name=extra/chromium state=present
      become: true
      tags: gui.chromium

    - name: Install Firefox
      community.general.pacman: name=extra/firefox state=present
      become: true
      tags: gui.firefox

    # https://brave.com
    - name: Install Brave
      kewlfft.aur.aur:
        use: yay
        name: brave-bin
        state: present
      tags: gui.brave

    # https://github.com/flameshot-org/flameshot
    - name: Install flameshot
      community.general.pacman: name=community/flameshot state=present
      become: true
      tags: gui.flameshot

    # https://dbeaver.io/
    - name: Install DBeaver
      community.general.pacman: name=community/dbeaver state=present
      become: true
      tags: gui.dbeaver

    - name: Install LibreOffice
      community.general.pacman: name=extra/libreoffice-fresh state=present
      become: true
      tags: gui.libreoffice

    # https://www.thunderbird.net
    - name: Install Thunderbird
      community.general.pacman: name=extra/thunderbird state=present
      become: true
      tags: gui.thunderbird

    - name: Install Slack desktop
      kewlfft.aur.aur:
        use: yay
        name: slack-desktop
        state: present
      tags: gui.slack

    # https://www.rstudio.com/
    - name: Install RStudio
      kewlfft.aur.aur:
        use: yay
        name: rstudio-desktop-bin
        state: present
      tags: gui.rstudio

    - name: Install Signal
      community.general.pacman: name=community/signal-desktop state=present
      become: true
      tags: gui.signal

    - name: Install Telegram
      community.general.pacman: name=community/telegram-desktop state=present
      become: true
      tags: gui.telegram

    # https://www.wireshark.org/
    - name: Install Wireshark
      block:
        - name: Install wireshark
          community.general.pacman:
            name:
              - community/wireshark-cli
              - community/wireshark-qt
            state: present

        # give the current user permission to capture packets
        - name: Add user to the wireshark group
          ansible.builtin.user:
            name: "{{ ansible_env.USER }}"
            groups: wireshark
            append: true
      become: true
      tags: gui.wireshark

    - name: Install VLC
      community.general.pacman: name=extra/vlc state=present
      become: true
      tags: gui.vlc

    # https://keepassxc.org/
    - name: Install keepassxc
      community.general.pacman: name=community/keepassxc state=present
      become: true
      tags: gui.keepassxc

    # https://wiki.gnome.org/Apps/Gthumb
    - name: Install gThumb
      community.general.pacman: name=extra/gthumb state=present
      become: true
      tags: gui.gthumb

    # https://github.com/Soft/xcolor
    - name: Install xcolor
      community.general.pacman: name=community/xcolor state=present
      become: true
      tags: gui.xcolor

    # https://ephtracy.github.io/
    - name: Install magicavoxel
      kewlfft.aur.aur:
        use: yay
        name: magicavoxel
        state: present
      tags: gui.magicavoxel

    - name: Install gnome-disk-utility
      community.general.pacman: name=extra/gnome-disk-utility state=present
      become: true
      tags: gui.gnome_disk_utility

    # https://meldmerge.org
    - name: Install meld
      community.general.pacman: name=extra/meld state=present
      become: true
      tags: gui.meld

    # https://www.vagrantup.com/
    - name: Install vagrant
      community.general.pacman: name=community/vagrant state=present
      become: true
      tags: gui.vagrant

    # https://www.virtualbox.org/
    - name: Install VirtualBox
      community.general.pacman:
        name:
          - community/virtualbox
          - community/virtualbox-guest-utils
        state: present
      become: true
      tags: gui.virtualbox

    - name: Install gnome-boxes
      community.general.pacman:
        name:
          - community/libvirt
          - community/gnome-boxes
          - community/virt-manager
        state: present
      become: true
      tags: gui.gnome_boxes
