---
- name: GUI
  hosts: all
  tags: gui
  tasks:
    # https://github.com/alacritty/alacritty
    - name: Install alacritty terminal
      pacman: name=community/alacritty state=present
      become: true
      tags: gui.alacritty

    # https://meldmerge.org
    - name: Install meld
      pacman: name=extra/meld state=present
      become: true
      tags: gui.meld

    # https://github.com/flameshot-org/flameshot
    - name: Install flameshot
      pacman: name=community/flameshot state=present
      become: true
      tags: gui.flameshot

    - name: Install gedit
      pacman: name=extra/gedit state=present
      become: true
      tags: gui.gedit

    - name: Install Chromium
      pacman: name=extra/chromium state=present
      become: true
      tags: gui.chromium

    - name: Install Chrome
      kewlfft.aur.aur:
        use: yay
        name: google-chrome
        state: present
      tags: gui.chrome

    - name: Install Firefox
      pacman: name=extra/firefox state=present
      become: true
      tags: gui.firefox

    # https://brave.com
    - name: Install Brave
      kewlfft.aur.aur:
        use: yay
        name: brave-bin
        state: present
      tags: gui.brave

    # https://wiki.archlinux.org/title/Visual_Studio_Code
    - name: Install vscode
      kewlfft.aur.aur:
        use: yay
        name: visual-studio-code-bin
        state: present
      become: true
      tags: gui.vscode

    - name: Install LibreOffice
      pacman: name=extra/libreoffice-fresh state=present
      become: true
      tags: gui.libreoffice

    - name: Install Slack desktop
      kewlfft.aur.aur:
        use: yay
        name: slack-desktop
        state: present
      tags: gui.slack

    # https://dbeaver.io/
    - name: Install DBeaver
      pacman: name=community/dbeaver state=present
      become: true
      tags: gui.dbeaver

    # https://www.rstudio.com/
    - name: Install RStudio
      kewlfft.aur.aur:
        use: yay
        name: rstudio-desktop-bin
        state: present
      tags: gui.rstudio

    - name: Install Signal
      pacman: name=community/signal-desktop state=present
      become: true
      tags: gui.signal

    - name: Install Telegram
      pacman: name=community/telegram-desktop state=present
      become: true
      tags: gui.telegram

    # https://www.wireshark.org/
    - name: Install Wireshark
      pacman:
        name:
          - community/wireshark-cli
          - community/wireshark-qt
        state: present
      become: true
      tags: gui.wireshark

    - name: Install VLC
      pacman: name=extra/vlc state=present
      become: true
      tags: gui.vlc

    # https://keepassxc.org/
    - name: Install keepassxc
      pacman: name=community/keepassxc state=present
      become: true
      tags: gui.keepassxc

    # https://wiki.gnome.org/Apps/Gthumb
    - name: Install gThumb
      pacman: name=extra/gthumb state=present
      become: true
      tags: gui.gthumb

    # https://github.com/Soft/xcolor
    - name: Install xcolor
      pacman: name=community/xcolor state=present
      become: true
      tags: gui.xcolor

    # https://ephtracy.github.io/
    - name: Install magicavoxel
      kewlfft.aur.aur:
        use: yay
        name: magicavoxel
        state: present
      tags: gui.magicavoxel

    - name: Install gnome-disk-utility
      pacman: name=extra/gnome-disk-utility state=present
      become: true
      tags: gui.gnome_disk_utility
