- name: SSH
  hosts: all
  tags: ssh
  tasks:
    - name: Set variables
      ansible.builtin.set_fact:
        vars_ssh:
          path: "{{ ansible_env.HOME }}/.ssh"
          key_identifier: "id_ed25519-workbench_{{ ansible_hostname }}"

    - name: Install ssh
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.libssh2 }}"
          - "{{ config.packages.pacman.openssh }}"
          - "{{ config.packages.pacman.libssh }}"
      become: true
      notify: SSH running

    - name: Create ssh user directory if not exist
      ansible.builtin.file:
        path: "{{ vars_ssh.path }}"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0700
        state: directory

    - name: Generate an OpenSSH keypair with ed25519
      community.crypto.openssh_keypair:
        path: "{{ vars_ssh.path }}/{{ vars_ssh.key_identifier }}"
        type: ed25519
        comment: "{{ vars_ssh.key_identifier }}"
        # TODO: passphrase: ?

    - name: Create user ssh config file
      ansible.builtin.blockinfile:
        path: "{{ vars_ssh.path }}/config"
        block: |
          # default for all
          Host *
            IdentityFile {{ vars_ssh.path }}/{{ vars_ssh.key_identifier }}
        # Because of the potential for abuse, this file must have strict
        # permissions: read/write for the user, and not accessible by others.
        # It may be group-writable, provided that the group in question
        # contains only the user.
        mode: 0600
        create: true
        state: present

    - name: Add current pub key to authorized keys for passwordless access
      ansible.builtin.blockinfile:
        path: "{{ vars_ssh.path }}/authorized_keys"
        marker_begin: "BEGIN ANSIBLE MANAGED BLOCK: ssh authorized_keys"
        marker_end: "END ANSIBLE MANAGED BLOCK: ssh authorized_keys\n\n# Add authorized public keys down below"
        block: |
          # current key '{{ vars_ssh.key_identifier }}.pub':
          {{ lookup('file', '{{ vars_ssh.path }}/{{ vars_ssh.key_identifier }}.pub') }}
        # This file is not highly sensitive, but the recommended permissions
        # are read/write for the user, and not accessible by others.
        mode: 0600
        create: true
        state: present

    - name: Change sshd_config
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          PasswordAuthentication no
          PubkeyAuthentication yes
          AuthorizedKeysFile .ssh/authorized_keys
      become: true

  handlers:
    - name: SSH running
      ansible.builtin.systemd:
        name: sshd
        state: started
        enabled: true
      become: true
