---
# General configuration
#
config:
  vars:
    workbench_dir: /opt/workbench

  # https://github.com/strboul/strboul/tree/master/gpg
  gpg:
    master_pub: 4C884872307BB096C0EB226D9DFB9FAB33E2BB02
    subkey_sign_pub: 2AA9C7006171519C
    subkey_encrypt_pub: D11E33ABD581057F
    subkey_authenticate_pub: 041DD261E197F428

  # alphabetically sorted within their groups
  packages:
    pacman:  # XXX rename as arch, not pacman?
      alacritty: community/alacritty
      archlinux_keyring: core/archlinux-keyring
      base_devel: base-devel
      bat: community/bat
      bind: extra/bind
      blueman: community/blueman
      bluez_utils: extra/bluez-utils
      bluez: extra/bluez
      chromium: extra/chromium
      clang: extra/clang
      code: community/code
      coreutils: core/coreutils
      ctags: extra/ctags
      cups: extra/cups
      curl: core/curl
      dbeaver: community/dbeaver
      deno: community/deno
      direnv: community/direnv
      docker_compose: community/docker-compose
      docker: community/docker
      etckeeper: community/etckeeper
      fd: community/fd
      file_roller: extra/file-roller
      firefox: extra/firefox
      firewalld: community/firewalld
      flameshot: community/flameshot
      fzf: community/fzf
      galculator: community/galculator
      gdu: community/gdu
      gedit: extra/gedit
      ghostscript: extra/ghostscript
      gimp: extra/gimp
      git: extra/git
      gnome_boxes: community/gnome-boxes
      gnome_disk_utility: extra/gnome-disk-utility
      gnu_free_fonts: extra/gnu-free-fonts
      gnu_netcat: extra/gnu-netcat
      golang: community/go
      gpgme: core/gpgme
      gthumb: extra/gthumb
      htop: extra/htop
      hyperfine: community/hyperfine
      inetutils: core/inetutils
      iputils: core/iputils
      jq: community/jq
      k9s: community/k9s
      keepassxc: community/keepassxc
      kubectx: community/kubectx
      lazygit: community/lazygit
      libreoffice_fresh: extra/libreoffice-fresh
      libssh2: core/libssh2
      libssh: extra/libssh
      libvirt: community/libvirt
      lsof: extra/lsof
      lua: extra/lua
      man_db: core/man-db
      meld: extra/meld
      minikube: community/minikube
      neofetch: community/neofetch
      neovim: community/neovim
      networkmanager_openvpn: extra/networkmanager-openvpn
      nmap: extra/nmap
      nodejs: community/nodejs
      noto_fonts_cjk: extra/noto-fonts-cjk
      noto_fonts_emoji: extra/noto-fonts-emoji
      noto_fonts_extra: extra/noto-fonts-extra
      noto_fonts: extra/noto-fonts
      npm: community/npm
      ntp: extra/ntp
      onefetch: community/onefetch
      openssh: core/openssh
      openvpn: extra/openvpn
      pass: community/pass
      peek: community/peek
      podman: community/podman
      pwgen: community/pwgen
      pyenv: community/pyenv
      qrencode: extra/qrencode
      r: community/r
      ranger: community/ranger
      ripgrep: community/ripgrep
      rust: extra/rust
      shellcheck: community/shellcheck
      signal_desktop: community/signal-desktop
      socat: extra/socat
      solaar: community/solaar
      strace: extra/strace
      tcpdump: extra/tcpdump
      telegram_desktop: community/telegram-desktop
      terraform: community/terraform
      thunderbird: extra/thunderbird
      tmux: community/tmux
      traceroute: core/traceroute
      tree: extra/tree
      vagrant: extra/vagrant
      valgrind: extra/valgrind
      viewnior: community/viewnior
      vim: extra/vim
      virt_manager: community/virt-manager
      virtualbox_guest_utils: community/virtualbox-guest-utils
      virtualbox: community/virtualbox
      vlc: extra/vlc
      wget: extra/wget
      wireguard_tools: extra/wireguard-tools
      wireshark_qt: community/wireshark-qt
      wireshark: community/wireshark-cli
      xclip: extra/xclip
      xcolor: community/xcolor
      xfce4_clipman_plugin: extra/xfce4-clipman-plugin
      xfce4_genmon_plugin: extra/xfce4-genmon-plugin
      xfce4_whiskermenu_plugin: community/xfce4-whiskermenu-plugin
      xorg_xev: extra/xorg-xev
      yubikey_manager_qt: community/yubikey-manager-qt
      yubikey_manager: community/yubikey-manager
      yubikey_touch_detector: community/yubikey-touch-detector
      zbar: extra/zbar
      zsh: extra/zsh

    # beware aur packages - audit them before you add here
    aur:
      brave_bin: brave-bin
      clang_format_static_bin: clang-format-static-bin
      google_chrome: google-chrome
      lazydocker: lazydocker
      magicavoxel: magicavoxel
      nerd_fonts_jetbrains_mono: nerd-fonts-jetbrains-mono
      slack_desktop: slack-desktop
      terraform_docs_bin: terraform-docs-bin
      terraform_ls: terraform-ls
      tflint_bin: tflint-bin
      visual_studio_code_bin: visual-studio-code-bin

# vim: ft=yaml.ansible
