---
- name: Main
  hosts: all
  gather_facts: true

# --- base
- import_playbook: playbooks/base/main.yml
- import_playbook: playbooks/ntp/main.yml
# --- bluetooth
- import_playbook: playbooks/bluetooth/main.yml
# --- language
- import_playbook: playbooks/language/main.yml
# --- package
- import_playbook: playbooks/package/main.yml
# --- gui
- import_playbook: playbooks/gui/main.yml
