---
- name: Work profile
  hosts: all
  gather_facts: true
  roles:
    - essential
    # - bluetooth
    - role: packages
      tags:
        - zsh
        - neovim
        - tmux
        - cli_utils
        - cli_fetch
