---
- name: pip install
  import_tasks: pip.yml

- name: npm install
  import_tasks: npm.yml

- name: Install Chrome browser
  yay: name=aur/google-chrome state=present
  tags:
    - work
    - personal

- name: Install Firefox browser
  yay: name=extra/firefox state=present
  tags:
    - personal

- name: Install Brave browser  # https://brave.com
  yay: name=aur/brave-bin state=present
  tags:
    - work
    - personal

- name: Install vscode
  yay: name=community/code state=present
  tags:
    - work
    - personal

- name: Install LibreOffice Fresh (EN)
  yay: name=extra/libreoffice-fresh state=present
  tags:
    - work
    - personal

- name: Install Slack desktop
  yay: name=aur/slack-desktop state=present
  tags:
    - work

- name: Install gedit
  yay: name=extra/gedit state=present
  tags:
    - work
    - personal

- name: Install podman  # https://podman.io/
  yay: name=community/podman state=present
  tags:
    - personal

- name: Install DBeaver  # https://dbeaver.io/
  yay: name=community/dbeaver state=present
  tags:
    - work
    - personal

- name: Install RStudio  # https://www.rstudio.com/
  yay: name=aur/rstudio-desktop-bin state=present
  tags:
    - personal

- name: Install virtualization software
  yay:
    name:
      - community/libvirt
      - community/gnome-boxes
      - community/virt-manager
      - aur/virtualbox-ext-oracle
      - community/vagrant  # https://www.vagrantup.com/
    state: present
  tags:
    - personal

- name: Install IMs
  yay:
    name:
      - community/signal-desktop
      - community/telegram-desktop
    state: present
  tags:
    - personal

- name: Install Terraform & tools  # https://www.terraform.io/
  yay:
    name:
      - community/terraform
      - aur/terraform-ls  # LSP for terraform https://github.com/hashicorp/terraform-ls
      - aur/tflint-bin  # https://github.com/terraform-linters/tflint
      - aur/terraform-docs-bin  # https://github.com/terraform-docs/terraform-docs
    state: present
  tags:
    - personal

- name: Install kubernetes tools
  yay:
    name:
      - community/k9s  # https://k9scli.io/
      - community/kubectx  # https://github.com/ahmetb/kubectx
      - community/minikube  # https://github.com/kubernetes/minikube
    state: present
  tags:
    - personal

- name: Install Wireshark  # https://www.wireshark.org/
  yay:
    name:
      - community/wireshark-cli
      - community/wireshark-qt
    state: present
  tags:
    - personal

- name: CLI fetch utilities
  yay:
    name:
      - community/neofetch  # https://github.com/dylanaraps/neofetch
      - community/onefetch  # https://github.com/o2sh/onefetch
    state: present
  tags:
    - personal

- name: Video
  yay:
    name:
      - extra/ffmpeg  # https://ffmpeg.org/
      - extra/vlc
    state: present
    tags:
      - personal

- name: Password manager
  yay:
    name:
      - community/keepassxc  # https://keepassxc.org/
    state: present
    tags:
      - personal

- name: Golang
  yay:
    name:
      - community/go
    state: present
  tags:
    - personal

- name: Deno  # https://deno.land/
  yay: name=community/deno state=present
  tags:
    - personal

- name: Rust
  yay:
    name:
      - extra/rust
    state: present
  tags:
    - personal

- name: C/C++
  yay:
    name:
      - extra/compiler-rt
      - extra/clang
      - aur/clang-format-static-bin
      - extra/valgrind
    state: present
  tags:
    - personal

- name: Other
  yay:
    name:
      - aur/dive  # https://github.com/wagoodman/dive
      - aur/magicavoxel
      - community/xcolor  # https://github.com/Soft/xcolor
    state: present
  tags:
    - personal
