---
- name: Language
  hosts: all
  tags: language
  tasks:
    - name: Install nodejs
      import_tasks: node.yml
      tags: language.node

    - name: Install R
      community.general.pacman: name=extra/r state=present
      become: true
      tags: language.r

    - name: Install golang
      community.general.pacman: name=community/go state=present
      become: true
      tags: language.golang

    # https://deno.land/
    - name: Install deno
      community.general.pacman: name=community/deno state=present
      become: true
      tags: language.deno

    - name: Install Rust
      community.general.pacman: name=extra/rust state=present
      become: true
      tags: language.rust
