---
- name: Language
  hosts: all
  tags: language
  tasks:
    - name: Install nodejs
      import_tasks: node.yml
      tags: language.node

    - name: Install R
      community.general.pacman: name=extra/r state=present
      become: true
      tags: language.r

    - name: Setup golang
      block:
        - name: Install golang
          community.general.pacman: name=community/go state=present
          become: true

        - name: Add golang paths
          ansible.builtin.blockinfile:
            path: "{{ item }}"
            marker: "# {mark} ANSIBLE MANAGED BLOCK: golang"
            block: |
              export PATH=$PATH:/usr/local/go/bin
              gopath="$(go env GOPATH)"
              export PATH=$PATH:"$gopath"/bin
            mode: 0644
            create: true
            state: present
          loop:
            - "{{ ansible_env.HOME }}/.zshenv"
            - "{{ ansible_env.HOME }}/.bash_profile"
      tags: language.golang

    # https://deno.land/
    - name: Install deno
      community.general.pacman: name=community/deno state=present
      become: true
      tags: language.deno

    - name: Install Rust
      community.general.pacman: name=extra/rust state=present
      become: true
      tags: language.rust

    - name: Install Lua
      community.general.pacman: name=extra/lua state=present
      become: true
      tags: language.lua
