---
- name: Install nodejs
  community.general.pacman: name=community/nodejs state=present
  become: true

- name: Setup npm
  block:
    - name: Install npm
      community.general.pacman: name=community/npm state=present
      become: true

    # https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
    - name: Don't require sudo access while installing global packages
      block:
        - name: Create a directory for global installations
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/.npm-global"
            owner: "{{ ansible_env.USER }}"
            group: "{{ ansible_env.USER }}"
            mode: 0755
            state: directory

        - name: Configure npm to use the new directory path
          ansible.builtin.command: "npm config set prefix '~/.npm-global'"
          changed_when: false

        - name: Export the path in profile
          ansible.builtin.blockinfile:
            path: "{{ item }}"
            marker: "# {mark} ANSIBLE MANAGED BLOCK: npm-global"
            block: |
              export PATH="~/.npm-global/bin:$PATH"
            mode: 0644
            create: true
            state: present
          loop:
            - "{{ ansible_env.HOME }}/.zprofile"
            - "{{ ansible_env.HOME }}/.bash_profile"
