# Manage Python with pyenv
#
# Reference:
#   https://github.com/pyenv/pyenv/blob/master/COMMANDS.md
#
# See the available versions
#   pyenv versions
#
# Install a version
#   pyenv install 3.10
#
# Set global version
#   pyenv global 3.10
#
# Set local version
# (This command creates a .python-version file in
# your current directory. If you have pyenv active
# in your environment, this file will automatically
# activate this version for you.)
#   pyenv local 3.10
#
# Temporarily set version
# (To quickly test, this command activates the version specified by setting the
# PYENV_VERSION environment variable.)
#   pyenv shell 3.10
#
- name: Setup Python
  hosts: all
  tags: python
  tasks:
    - name: Install pyenv
      community.general.pacman: name=community/pyenv state=present
      become: true

    - name: Add pyenv to the profile
      ansible.builtin.blockinfile:
        path: "{{ item }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
        mode: 0644
        create: true
        state: present
      loop:
        - "{{ ansible_env.HOME }}/.zshenv"
        - "{{ ansible_env.HOME }}/.bash_profile"

    - name: Install pyenv versions
      ansible.builtin.command:
        argv:
          - pyenv
          - install
          - -v
          - "{{ item }}"
          - --skip-existing
        creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ item }}"
      loop:
        - "3.8.0"
        - "3.9.0"
        - "3.10.0"
      register: pyenv_install
      notify: Set default pyenv version

  handlers:
    # Set the highest Python version as global initially.
    - name: Set default pyenv version
      ansible.builtin.command: |
        pyenv global "$(pyenv versions | sort -r --version-sort | sed -n 2p | xargs)"
