# Follow the post-install steps here for the rest:
# https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
#
- name: Setup Docker
  hosts: all
  tags: docker
  tasks:
    - name: Install Docker
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.docker }}"
          - "{{ config.packages.pacman.docker-compose }}"
        state: present
      become: true
      notify: Docker service running

    - name: Create the docker group
      ansible.builtin.group:
        name: docker
        state: present
      become: true

    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: true
      become: true

    # force ansible run the notified handlers up to this point
    - meta: flush_handlers

    - name: Change the group ownership of the docker socket
      ansible.builtin.file:
        path: /var/run/docker.sock
        owner: "{{ ansible_env.USER }}"
      become: true

    # TODO: do try, fail: if fail print a message and fail to be more explicit.
    - name: Test run Docker
      ansible.builtin.command: docker run --rm hello-world
      changed_when: false

  handlers:
    - name: Docker service running
      ansible.builtin.systemd:
        name: docker.service
        state: started
        enabled: true
      become: true
