- name: Packages
  hosts: all
  tags: packages
  vars:
    zsh_command: /usr/bin/zsh
  tasks:
    - name: Setup zsh
      import_tasks: zsh.yml
      tags: packages.zsh

    - name: Setup neovim
      import_tasks: nvim.yml
      tags: packages.nvim

    - name: Setup tmux
      import_tasks: tmux.yml
      tags: packages.tmux

    - name: Setup Docker
      import_tasks: docker.yml
      tags: packages.docker

    - name: pip installs
      import_tasks: pip.yml
      tags: packages.pip

    - name: npm installs
      import_tasks: npm.yml
      tags: packages.npm

    - name: cli utils install
      import_tasks: cli-utils.yml
      tags: packages.cli_utils

    - name: Install Terraform
      import_tasks: terraform.yml
      tags: packages.terraform

    - name: Install Kubernetes
      import_tasks: kubernetes.yml
      tags: packages.kubernetes
