---
- name: Install nvim  # https://github.com/neovim/neovim
  pacman: name=community/neovim state=present
  become: true

- name: Setup vim-plug
  vars:
    vim_plug_path: "$HOME/.local/share/nvim/site/autoload/plug.vim"
  block:
    - name: Install vim-plug
      shell: |
        sh -c 'curl -fLo "{{ vim_plug_path }}" --create-dirs \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      args:
        creates: "{{ vim_plug_path }}"
      changed_when: false

    - name: Install vim-plug plugins
      command: "nvim +PlugInstall +qall"
      changed_when: false

    - name: Install coc-nvim plugins
      command: "nvim +CocUpdateSync +qall"
      changed_when: false

- name: Install neovim tools
  pacman:
    name:
      - extra/ctags  # https://github.com/universal-ctags/ctags
    state: present
  become: true

- name: Install pynvim  # see `:h provider-python` in neovim
  pip: name=pynvim state=present
