- name: Bluetooth
  hosts: all
  tags: bluetooth
  vars:
    bluetooth_conf_path: /etc/bluetooth/main.conf
  tasks:
    - name: Install bluetooth tools
      pacman:
        name:
          - extra/bluez
          - extra/bluez-utils
        state: present
      become: true

    - name: Check if bluetooth conf file exists
      stat:
        path: "{{ bluetooth_conf_path }}"
      register: bluetooth_conf_file

    # https://gist.github.com/andrebrait/961cefe730f4a2c41f57911e6195e444#enable-bluetooth-fast-connect-config
    - name: Enable bluetooth fast connect config
      lineinfile:
        path: "{{ bluetooth_conf_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^#ReconnectAttempts=", line: "ReconnectAttempts=7" }
        - { regexp: "^#ReconnectIntervals=", line: "ReconnectIntervals=1,2,8" }
        - { regexp: "^#FastConnectable=", line: "FastConnectable=true" }
      become: true
      when: bluetooth_conf_file.stat.exists
