Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # set the VM app name
  config.vm.define "test_vagrant_workbench" do |app|
  end

  config.vm.hostname = "test-archlinux"
  config.vm.network "private_network", ip: "192.168.56.2"
end
