# Xfce Desktop Environment
#
# https://www.xfce.org/
#
- name: xfce4
  hosts: all
  tags: xfce4
  tasks:
    - name: Install Xorg utils
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.xorg_xev }}"  # print contents of X events
        state: present
      become: true

    - name: Install xfce4 plugins
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.xfce4_whiskermenu_plugin }}"
          - "{{ config.packages.pacman.xfce4_clipman_plugin }}"
          - "{{ config.packages.pacman.xfce4_genmon_plugin }}"
        state: present
      become: true

    - name: Install other relevant programs
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.galculator }}"
          - "{{ config.packages.pacman.blueman }}"
          - "{{ config.packages.pacman.viewnior }}"
          - "{{ config.packages.pacman.file_roller }}"
          - "{{ config.packages.pacman.flameshot }}"  # Screenshot | https://github.com/flameshot-org/flameshot
          - "{{ config.packages.pacman.peek }}"  # GIF recorder | https://github.com/phw/peek
        state: present
      become: true

    - name: Apply xfconf-query commands
      ansible.builtin.command: "sh {{ ansible_env.PWD }}/xfconf-query.sh"
      changed_when: false

    - name: Copy files (if not exist)
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0644
      loop:
        - { src: "{{ ansible_env.PWD }}/whiskermenu-1.rc", dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/whiskermenu-1.rc" }
        - { src: "{{ ansible_env.PWD }}/genmon-90.rc", dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/genmon-90.rc" }

    - name: Remap caps lock to escape in the keyboard
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.xprofile"
        block: |
          setxkbmap -option caps:escape
        mode: 0644
        create: true
        state: present
