# TODO: move to firewalld
# Manage firewall with UFW
#
# List rules
#   sudo ufw status verbose
#
# List logs
#   sudo ls /var/log/ufw*
#
# Disable ufw completely and delete all rules
#   sudo ufw reset
#
# Delete rules by rule number
#   sudo ufw status numbered
#   sudo ufw delete 1
#
- name: ufw
  hosts: all
  tags: ufw
  vars:
    # https://datatracker.ietf.org/doc/html/rfc1918#section-3
    rfc1918_blocks:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
  tasks:
    - name: Install ufw
      community.general.pacman: name=community/ufw state=present
      become: true
      notify: ufw running

    - name: Enable ufw and reject everything by default
      community.general.ufw:
        state: enabled
        policy: reject
        log: true
      become: true

    # "medium" logs all blocked or allowed packets, and packets not matching
    # policies
    - name: Set logging
      community.general.ufw:
        logging: medium
      become: true

    # ufw supports connection rate limiting, which is useful for protecting
    # against brute-force login attacks. ufw will deny connections if an IP
    # address has attempted to initiate 6 or more connections in the last 30
    # seconds. See  http://www.debian-administration.org/articles/187 for
    # details. Typical usage is:
    - name: Limit ssh port
      community.general.ufw:
        rule: "limit"
        port: ssh
        proto: tcp
        src: "{{ item }}"
      loop: "{{ rfc1918_blocks }}"
      become: true

    - name: Allow port
      community.general.ufw:
        rule: allow
        port: 3333
        proto: tcp
        comment: my socat port
        src: "{{ item }}"
      loop: "{{ rfc1918_blocks }}"
      become: true

    - name: Allow port range
      community.general.ufw:
        rule: allow
        port: 19000:19020
        proto: tcp
        comment: expo.dev
        src: "{{ item }}"
      loop: "{{ rfc1918_blocks }}"
      become: true

  handlers:
    - name: ufw running
      ansible.builtin.service:
        name: ufw
        state: started
        enabled: true
      become: true
