---
- name: Install Docker
  yay:
    name:
      - community/docker
      - community/docker-compose
    state: present

- name: Setup Docker
  block:
    - name: Create the docker group
      group:
        name: docker
        state: present

    - name: Add your user to the docker group
      user:
        name: docker
        group: "{{ ansible_env.USER }}"

    # Follow the post-install steps here for the rest:
    # https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
    #
    # reboot & reload is needed to have Docker ready.
    # check the daemon with: `systemctl status docker`
  become: true
  become_method: sudo
