---
- name: Install clang
  community.general.pacman: name=extra/clang state=present
  become: true

- name: Install valgrind
  community.general.pacman: name=extra/valgrind state=present
  become: true

- name: Install clang-format
  kewlfft.aur.aur:
    use: yay
    name: clang-format-static-bin
    state: present
