---
- name: Install Kubernetes tools
  community.general.pacman:
    name:
      - community/k9s  # https://k9scli.io/
      - community/kubectx  # https://github.com/ahmetb/kubectx
      - community/minikube  # https://github.com/kubernetes/minikube
    state: present
  become: true
