- name: Package
  hosts: all
  tags: package
  tasks:
    - name: Setup zsh
      ansible.builtin.import_tasks: zsh.yml
      tags: package.zsh

    - name: Setup neovim
      ansible.builtin.import_tasks: nvim.yml
      tags: package.nvim

    - name: Setup tmux
      ansible.builtin.import_tasks: tmux.yml
      tags: package.tmux

    - name: cli utils install
      ansible.builtin.import_tasks: cli-utils.yml
      tags: package.cli_utils

    - name: cli utils extra install
      ansible.builtin.import_tasks: cli-utils-extra.yml
      tags: package.cli_utils_extra

    - name: npm installs
      ansible.builtin.import_tasks: npm.yml
      tags: package.npm

    - name: Setup podman
      ansible.builtin.import_tasks: podman.yml
      tags: package.podman

    - name: Setup Terraform
      ansible.builtin.import_tasks: terraform.yml
      tags: package.terraform

    - name: Setup Kubernetes
      ansible.builtin.import_tasks: kubernetes.yml
      tags: package.kubernetes

    - name: Setup C/C++ tools
      ansible.builtin.import_tasks: c-cpp-tools.yml
      tags: package.c_cpp_tools

    - name: Setup wireguard
      ansible.builtin.import_tasks: wireguard.yml
      tags: package.wireguard
