- name: Package
  hosts: all
  tags: package
  vars:
    zsh_command: /usr/bin/zsh
  tasks:
    - name: Setup zsh
      import_tasks: zsh.yml
      tags: package.zsh

    - name: Setup neovim
      import_tasks: nvim.yml
      tags: package.nvim

    - name: Setup tmux
      import_tasks: tmux.yml
      tags: package.tmux

    - name: cli utils install
      import_tasks: cli-utils.yml
      tags: package.cli_utils

    - name: pip installs
      import_tasks: pip.yml
      tags: package.pip

    - name: npm installs
      import_tasks: npm.yml
      tags: package.npm

    - name: Install Terraform
      import_tasks: terraform.yml
      tags: package.terraform

    - name: Install Kubernetes
      import_tasks: kubernetes.yml
      tags: package.kubernetes

    - name: Install C/C++ tools
      import_tasks: c-cpp-tools.yml
      tags: package.c_cpp_tools
