---
- name: Python tools
  pip:
    name:
      - virtualenv
      - pylint  # https://github.com/PyCQA/pylint
      - bpython  # https://github.com/bpython/bpython
      - pdbpp  # https://github.com/pdbpp/pdbpp (drop-in replacement for pdb)
    state: present
  tags: package.pip.python_tools

- name: Data science tools
  pip:
    name:
      - jupyter
      - radian  # https://github.com/randy3k/radian
    state: present
  tags: package.pip.ds_tools

- name: Other tools
  pip:
    name:
      - tmuxp  # https://github.com/tmux-python/tmuxp
      - youtube-dl  # https://github.com/ytdl-org/youtube-dl
      - visidata  # https://www.visidata.org/
    state: present
  tags: package.pip.other_tools
