---
- name: Install zsh
  pacman: name=extra/zsh state=present
  become: true

# add --unattended not to start the interactive prompt upon installation
# https://github.com/ohmyzsh/ohmyzsh#unattended-install
- name: Install oh-my-zsh
  shell: |
    script="$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
      sh -c "$script" "" --unattended
  args:
    # when this file exists, this step won't run.
    creates: ~/.oh-my-zsh
  changed_when: false

- name: Use the pre .zshrc file if it exists
  block:
    - name: Check pre .zshrc file exists
      stat:
        path: "$HOME/.zshrc.pre-oh-my-zsh"
      register: pre_zshrc_file

    - name: Rename pre .zshrc file
      command: "mv {{ item.from }} {{ item.to }}"
      loop:
        - { from: "$HOME/.zshrc.pre-oh-my-zsh", to: "$HOME/.zshrc" }
      when: pre_zshrc_file.stat.exists

- name: oh-my-zsh custom dir
  shell: "echo ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
  register: "oh_my_zsh_custom_dir"
  changed_when: false

- name: Install oh-my-zsh plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ oh_my_zsh_custom_dir.stdout }}/plugins/{{ item.dest }}"
    depth: 1
    version: master
    update: false
  loop:
    - { repo: "https://github.com/zsh-users/zsh-autosuggestions.git", dest: "zsh-autosuggestions" }
    - { repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git", dest: "zsh-syntax-highlighting" }
    - { repo: "https://github.com/zsh-users/zsh-history-substring-search.git", dest: "zsh-history-substring-search" }

- name: Install powerlevel10k prompt
  block:
    - name: Install p10k
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ oh_my_zsh_custom_dir.stdout }}/themes/powerlevel10k"
        depth: 1
        version: master
        update: false

    - name: Disable p10k configuration wizard prompt
      blockinfile:
        path: "{{ item }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: p10k"
        block: |
          POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
        mode: 0644
        create: true
        state: present
      loop:
        - "{{ ansible_env.HOME }}/.zprofile"

- name: Add zsh to /etc/shells
  lineinfile:
    line: "{{ zsh_command }}"
    dest: /etc/shells
    state: present
  become: true

- name: Change default shell to zsh
  command:
    cmd: "chsh -s {{ zsh_command }} {{ ansible_env.USER }}"
  changed_when: false
  become: true
