# Firewalld
# https://wiki.archlinux.org/title/Firewalld
#
# sudo firewall-cmd --get-active-zones
# sudo firewall-cmd --list-all
#
- name: firewalld
  hosts: all
  tags: firewalld
  tasks:
    - name: Install firewalld
      community.general.pacman: name="{{ config.packages.pacman.firewalld }}" state=present
      become: true
      notify: firewalld running

    # TODO: should it be --zone=home?
    - name: Allow port range (expo.dev)
      ansible.builtin.shell: |
        firewall-cmd --zone=public --add-port=19000-19100/tcp --permanent
        firewall-cmd --reload
      changed_when: false
      become: true

    - name: Allow port range (my socat)
      ansible.builtin.shell: |
        firewall-cmd --zone=public --add-port=3333/tcp --permanent
        firewall-cmd --reload
      changed_when: false
      become: true

  handlers:
    - name: firewalld running
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      become: true
