- name: NTP  # https://wiki.archlinux.org/title/Network_Time_Protocol_daemon
  hosts: all
  tasks:
    - name: Ensure NTP is installed
      pacman: name=extra/ntp state=present
      become: true
      notify:
        - NTP is running

  handlers:
    - name: NTP is running
      service:
        name: systemd-timesyncd
        state: started
        enabled: true
