# https://wiki.archlinux.org/title/Network_Time_Protocol_daemon
- name: NTP
  hosts: all
  tags: ntp
  tasks:
    - name: Ensure NTP is installed
      community.general.pacman: name=extra/ntp state=present
      become: true
      notify: NTP running

  handlers:
    - name: NTP running
      ansible.builtin.service:
        name: systemd-timesyncd
        state: started
        enabled: true
      become: true
